version: '3.8'

services:
  polybot:
    image: ${POLYBOT_IMG_NAME}
    container_name: polybot
    environment:
        TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
        TELEGRAM_APP_URL: ${TELEGRAM_APP_URL}
        S3_BUCKET_NAME: ${S3_BUCKET_NAME}
        YOLO5_URL: ${YOLO5_URL}
        DYNAMODB_TABLE: ${DYNAMODB_TABLE}
        AWS_REGION: ${AWS_REGION}
        SQS_URL: ${SQS_URL}
    volumes:
      - ./logs:/usr/src/app/logs
    restart: always
