version: '3.8'

services:
  polybot:
    image: ${POLYBOT_IMG_NAME}
    container_name: polybot
    ports:
      - "8443:8443"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_APP_URL: ${TELEGRAM_APP_URL}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      YOLO5_URL: ${YOLO5_URL}
      DYNAMODB_TABLE: ${DYNAMODB_TABLE}
      AWS_REGION: ${AWS_REGION}
      SQS_URL: ${SQS_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./logs:/usr/src/app/logs
    restart: always
