version: '3.8'

services:
  yolo5:
    build: .
    container_name: yolo5
    ports:
      - "8081:8081"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_APP_URL: ${TELEGRAM_APP_URL}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      YOLO5_URL: ${YOLO5_URL}
      DYNAMODB_TABLE: ${DYNAMODB_TABLE}
      AWS_REGION: ${AWS_REGION}
      SQS_URL: ${SQS_URL}
    volumes:
      - ./data:/usr/src/app/data
    restart: always
