version: '3.8'

services:
  yolo5:
    build: .
    container_name: yolo5
    ports:
      - "8081:8081"
    environment:
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      DYNAMODB_TABLE: ${DYNAMODB_TABLE}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - ./data:/usr/src/app/data
    restart: always


