version: '3.8'

services:
  yolo5:
    image: yolo5:latest
    container_name: yolo5
    ports:
      - "8081:8081"
    environment:
      AWS_REGION: $AWS_REGION
      DYNAMODB_TABLE: $DYNAMODB_TABLE
      S3_BUCKET_NAME: $S3_BUCKET_NAME
    volumes:
      - ./data:/usr/src/app/data
    restart: always
