version: '3.8'
services:
  yolo5:
    image: yolo5:v1
    environment:
      - SQS_URL=${SQS_URL}
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_TABLE=${DYNAMODB_TABLE}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - POLYBOT_URL=${POLYBOT_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./yolo5:/usr/src/app
    depends_on:
      - dynamodb
      - sqs


