version: '3.8'
services:
  yolo5:
    image: ${YOLO5_IMG_NAME}
    container_name: yolo5
    environment:
      AWS_REGION: ${AWS_REGION}
      DYNAMODB_TABLE: ${DYNAMODB_TABLE}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      SQS_URL: ${SQS_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./logs:/usr/src/app/logs
    restart: always
    depends_on:
      - dynamodb


