name: Polybot Microservice Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 15.236.39.168  # Replace with your actual EC2 public IP if different

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          cd polybot
          docker pull -t ${{ secrets.DOCKER_USERNAME }}/polybot:latest .
          docker run -d
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/polybot:latest

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Prepare SSH key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      - name: Deploy new version to EC2
        run: |
          ssh -i /home/runner/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ env.EC2_PUBLIC_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/polybot:latest
          docker stop polybot || true
          docker rm polybot || true
          docker run -d --name polybot ${{ secrets.DOCKER_USERNAME }}/polybot:latest
          EOF
