name: Yolo5 Microservice Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 15.236.204.154

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          cd yolo5
          docker-compose build -t ${{ secrets.DOCKER_USERNAME }}/yolo5:${{ github.run_number }} .
          docker-compose push ${{ secrets.DOCKER_USERNAME }}/yolo5:${{ github.run_number }}

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Prepare SSH key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      - name: Deploy new version to EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
          # Create the .env file with required secrets
          echo "YOLO5_IMG_NAME=${{ secrets.DOCKER_USERNAME }}/yolo5:${{ github.run_number }}" > /home/ubuntu/projects/AWSProject-bennyi/yolo5/.env
          echo "AWS_REGION=eu-west-3" >> /home/ubuntu/projects/AWSProject-bennyi/yolo5/.env
          echo "DYNAMODB_TABLE=AWS-Project-Predictions-bennyi" >> /home/ubuntu/projects/AWSProject-bennyi/yolo5/.env
          echo "S3_BUCKET_NAME=bennyi-aws-s3-bucket" >> /home/ubuntu/projects/AWSProject-bennyi/yolo5/.env
          # Manage Docker containers
          cd /home/ubuntu/projects/AWSProject-bennyi/yolo5
          docker-compose down
          docker-compose up -d
          EOF
