name: Yolo5 Microservice Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 15.236.204.154

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker-compsoe --version
          cd yolo5
          docker-compsoe build -t ${{ secrets.DOCKER_USERNAME }}/yolo5:latest .
          docker-compose push ${{ secrets.DOCKER_USERNAME }}/yolo5:latest

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Prepare SSH key
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa

      - name: Deploy new version to EC2
        with:
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          ssh -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ubuntu@${{ env.EC2_PUBLIC_IP }} << 'EOF'
          docker-compose build ${{ secrets.DOCKER_USERNAME }}/yolo5:latest
          docker run -d --name yolo5 ${{ secrets.DOCKER_USERNAME }}/yolo5:latest
          EOF
