name: Yolo5 Microservice Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 13.37.252.11  # Replace with your actual EC2 public IP if different

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          cd yolo5
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yolo5:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/yolo5:latest

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Deploy new version to EC2
        run: |
          ssh -i "${{ secrets.EC2_SSH_PRIVATE_KEY }}" ec2-user@${{ env.EC2_PUBLIC_IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/yolo5:latest
          docker stop yolo5 || true
          docker rm yolo5 || true
          docker run -d --name yolo5 ${{ secrets.DOCKER_USERNAME }}/yolo5:latest
          EOF
