name: Yolo5 Microservice Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: 15.237.252.29


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          cd yolo5
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yolo5:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/yolo5:${{ github.run_number }}

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Copy the entire yolo5 directory to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: yolo5/
          target: /home/ubuntu/projects/AWSProject-bennyi/
          debug: true

      - name: Update Docker Compose project on EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Update packages and install dependencies
            sudo apt-get update -y
            sudo apt-get install -y jq curl

            # Install Docker and Docker Compose
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

            # Ensure Docker Compose binary is in the PATH
            if ! command -v docker-compose &> /dev/null
            then
              echo "Docker Compose not found, installing..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Create the .env file with required secrets
            echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" > /home/ubuntu/projects/AWSProject-bennyi/polybot/.env
            echo "AWS_REGION=eu-west-3" > /home/ubuntu/projects/AWSProject-bennyi/yolo5/.env
            echo "DYNAMODB_TABLE=AWS-Project-Predictions-bennyi" >> /home/ubuntu/projects/AWSProject-bennyi/yolo5/.env
            echo "S3_BUCKET_NAME=bennyi-aws-s3-bucket" >> /home/ubuntu/projects/AWSProject-bennyi/yolo5/.env
            echo "YOLO5_IMG_NAME=${{ secrets.DOCKER_USERNAME }}/yolo5:${{ github.run_number }}" >> /home/ubuntu/projects/AWSProject-bennyi/yolo5/.env
            echo "SQS_URL='https://sqs.eu-west-3.amazonaws.com/019273956931/aws-sqs-image-processing-bennyi'" >> /home/ubuntu/projects/AWSProject-bennyi/yolo5/.env
            echo "TELEGRAM_APP_URL='https://aws-polybot-lb-bennyi-1016622634.eu-west-3.elb.amazonaws.com'" >> /home/ubuntu/projects/AWSProject-bennyi/yolo5/.env
            # Login to Docker Hub
            echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Manage Docker containers
            cd /home/ubuntu/projects/AWSProject-bennyi/yolo5
            docker-compose down
            docker-compose up -d
